[build]
  # Directory with the serverless Lambda functions
  functions = "lambda_functions"

[functions]
  # Directory with serverless functions, including background 
  # functions, to deploy. This is relative to the base directory
  # if one has been set, or the root directory if
  # a base hasn’t been set.
  directory = "functions/"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = 'GET, POST, OPTIONS, PUT, PATCH, DELETE'

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "/api/*"
  to = “https://murmuring-hollows-26750.herokuapp.com/api/:splat"
  status = 200
